### ISSUE TITLE
Help with removing Metadata Items from Conversion

### ISSUE THREAD

**Issue by kaiwei** [beancount/ledger2beancount#191]
Hi all,

I am unfortunately not a programmer so I've been scratching my head on how to prevent two items (namely CSV & MD5Sum) in my Ledger journal entries from showing up in the Beancount import. 

Right now this is what is in my ledger file:
> 2020-06-01 * UMS - DBSSSGSGXXX00
>     ; MD5Sum: 81f4d96a4c92746dc6f913378dbbcd09
>     ; CSV: "							01/06/2020",UMS - DBSSSGSGXXX00 ,USD,,9,"18.24 CR","18.24 CR"
>     Expenses:Unknown                                                USD -9
>     Assets:PREFERRED-CURRENT

Post conversion, I see the following notes in the output:
> ; ledger2beancount conversion notes:
> ;
> ;   - Metadata key CSV renamed to cSV
> ;   - Metadata key MD5Sum renamed to mD5Sum

Of which I then see the below:
> 2020-06-01 * "UMS - DBSSSGSGXXX00"
>   mD5Sum: "81f4d96a4c92746dc6f913378dbbcd09"
>   cSV: "\"							01/06/2020\",UMS - DBSSSGSGXXX00 ,USD,,9,\"18.24 CR\",\"18.24 CR\""
>   Expenses:Unknown                                                -9 USD
>   Assets:PREFERRED-CURRENT

In the YML config file, I tried

> A marker that tells ledger2beancount to ignore a line if the
> marker is found.
> ignore_marker: NoL2B
> ignore_marker: CSV
> ignore_marker: MD5Sum

And I also tried:

> You can set the following metadata tags to an empty string if you
> don't want the metadata to be added to beancount.
> postdate_tag: date
> auxdate_tag: aux-date
> code_tag: code
> CSV: ""
> MD5Sum: ""

Which all do not work. Any help? Thank you for the kind guidance.

**Comment by tbm** [comment]
> A marker that tells ledger2beancount to ignore a line if the
> marker is found.
> ignore_marker: NoL2B

The ignore_marker has to appear as a ledger comment.  A meta-data tag is not a ledger comment, so it won't work there.

> You can set the following metadata tags to an empty string if you
> don't want the metadata to be added to beancount.

This only works for the 3 named tags. These are special variables for things that don't exist in beancount so the information can (optionally) be saved as meta-data tags in beancount.

Did you read the [user guide](https://github.com/beancount/ledger2beancount/blob/master/docs/guide.md) to learn about these options?  If the options are not clear after reading the user guide, please let me know so we can improve the docs.

> Which all do not work. Any help? Thank you for the kind guidance.

There is no option to ignore specific metadata tags.  I don't think it makes sense to add such an option.  If the info is in ledger, it should be in beancount.  If you don't want it in beancount, don't put it in ledger.

Anyway, there's a simple solution for this: just run the ledger file or the converted beancount file through `grep -v` to remove the meta-data you don't want.

Specifically in your example, you can run

```
beancount foo.ledger | grep -v -E "^ +(cSV|mD5Sum):" > foo.beancount
```

This will remove all tags "cSV" and "mD5Sum" from the generated beancount file.
