### ISSUE TITLE
Inline Multiplication not processed

### ISSUE THREAD

**Issue by colindean** [beancount/ledger2beancount#192]
Giving ledger2beancount a try after using the old Python script for a long time. I've hit a problem with inline math, specifically multiplication. My actual salary can vary from period to period, so I use multiplication to calculate the match like so.

```
$ cat test.ledger
2019/12/31 Paycheck
  Income:Salary   -4000.00 USD
  Assets:Bank      4000.00 USD
  Income:401k:Match         (-4000.00 USD * 0.05)
  Assets:Investments:401k    (4000.00 USD * 0.05)

$ ledger -f test.ledger bal
         4200.00 USD  Assets
         4000.00 USD    Bank
          200.00 USD    Investments:401k
        -4200.00 USD  Income
         -200.00 USD    401k:Match
        -4000.00 USD    Salary
--------------------
                   0

$ scripts/ledger2beancount/bin/ledger2beancount --config scripts/ledger2beancount.yml test.ledger
option "operating_currency" "USD"
* Options

option "title" "Beancount export"
option "operating_currency" "USD"

2016-01-01 custom "fava-option" "show-accounts-with-zero-balance" "False"

2016-01-01 query "fava" "journal"
1970/01/01 open Assets:Bank
1970/01/01 open Assets:Investments:401k
1970/01/01 open Income:401k:Match
1970/01/01 open Income:Salary

1970/01/01 commodity USD

2019-12-31 txn "Paycheck"
  Income:Salary   -4000.00 USD
  Assets:Bank      4000.00 USD
  Income:401k:Match         (-4000.00) USD
  Assets:Investments:401k    (4000.00) USD
```

The result is that Fava is showing my 401k match as A LOT higher than it should be 😉 

For reference, my ledger2beancount.yml:

```yaml
---
date_format: "%Y/%m/%d"
date_format_no_year: "%m-%d"
account_open_date: 1970/01/01
commodities_date: 1970/01/01
beancount_indent: 2
ledger_indent: 4
operating_currencies:
- USD
hledger: false
beancount_header: scripts/beancount_headers.beancount
automatic_declarations: true
decimal_comma: false
convert_virtual: false
metadata_map:
  x-payee: payee
  x-payer: payer
payee_tag: payee
payer_tag: payer
payee_split: []
payee_match: []
account_map:
  Equity:OpeningBalances: Equity:OpeningBalances
account_regex:
  "^Accrued:Accounts Payable:(.*)": Liabilities:Accounts-Payable:$1
  "^Accrued:Accounts Receivable:(.*)": Assets:Accounts-Receivable:$1
commodity_map:
  "$": USD
  "£": GBP
  "€": EUR
  "¥": JPY
postdate_tag: date
auxdate_tag: aux-date
code_tag: code
link_match:
- "^\\d\\d\\d\\d-\\d\\d-\\d\\d-"
link_tags: []
currency_is_commodity:
- BTC
- ETH
- IBM
commodity_is_currency:
- MARRIOTT
- MILESMORE
- NECTAR
keep_marker: L2Bonly
```

**Comment by tbm** [comment]
At the moment the script assumes the commodity is last, so if you swap it around it would work:

```
2019-12-31 Paycheck
  Income:Salary   -4000.00 USD
  Assets:Bank      4000.00 USD
  Income:401k:Match         (0.05 * -4000.00 USD)
  Assets:Investments:401k    (0.05 * 4000.00 USD)
```

I'm not sure what the real solution is.  The problem is that value expressions in ledger can be quite complex, especially since ledger allows so many variants of how to express a commodity (10$, $10, 10 USD, USD 10, ...).  The real solution would probably be to write some kind of parser...

**Comment by tbm** [comment]
But ledger2beancount should also least produce a warning when it ignores certain stuff, so you don't get a shock due to your newfound riches. ;)

**Comment by colindean** [comment]
Confirmed:
```ledger
2019/12/31 Paycheck
  Income:Salary   -4000.00 USD
  Assets:Bank      4000.00 USD
  Income:401k:Match         (0.05 * -4000.00 USD)
  Assets:Investments:401k    (0.05 * 4000.00 USD)
```
```beancount
2019-12-31 txn "Paycheck"
  Income:Salary   -4000.00 USD
  Assets:Bank      4000.00 USD
  Income:401k:Match         (0.05 * -4000.00) USD
  Assets:Investments:401k    (0.05 * 4000.00) USD
```

And yes, communicating the ignored parts would be great! Thank you for the quick response.

**Comment by tbm** [comment]
Does that workaround work for you for now?  If not, I can see if I can come up with an ugly hack now.  If yes, I'll look into this in more detail later.

**Comment by colindean** [comment]
Yes, that worked. A quick find and replace and I'm back on the road.

**Comment by tbm** [comment]
Ok, great!

**Comment by tbm** [comment]
Hey Colin, your bug report prompted me into rewriting the parsing of postings.  This was a longstanding action item but a very low  priority one since the current code works (but is very ugly).  The new code is much cleaner.  And as it turns out, it's about 20% faster.

You get an error now when inline math can't be parsed.  This is in commit bf3e1761e32

I haven't actually *improved* the parsing of inline math though.  I can't figure out a good way to do it... we'll see...

**Comment by tbm** [comment]
I finally thought of a way to address this without actually parsing the math.   Your original example will work with the change.
