### ISSUE TITLE
Understand ledger default date formats without config

### ISSUE THREAD

**Issue by tbm** [beancount/ledger2beancount#195]
In the early days of ledger2beancount Zack and I debated date parsing.  IIRC I wanted to support a number of different formats whereas @zacchiro was strongly in favour of having the user configure the date format.

I'd like to circle back to this.  I think it would be useful for ledger2beancount to understand the default formats that ledger accepts.  This is a small set; see `times_initialize()` in `times.cc`

Basically, I'd like to add support for the following without config file:

```
06/22 %m/%d
    Assets:Test                        20.00 EUR
    Assets:Test

2020/06/22 %Y/%m/%d
    Assets:Test                        20.00 EUR
    Assets:Test

2020-06-22 %Y-%m-%d
    Assets:Test                        20.00 EUR
    Assets:Test
```

Ledger also supports this but I'm not sure there's much value:

```
2020/06 %Y/%m
    Assets:Test                        20.00 EUR
    Assets:Test
```

(the day is always 01)

According to `times.cc` ledger also supports `%y/%m/%d` (i.e. years with 2 digits) but that doesn't actually work for me:

```
> 20/06/22 %y/%m/%d
Error: Year is out of valid range: 1400..9999
```

@zacchiro any objections to add this?

One use case: running ledger2beancount over the ledger test suite, which uses a mix of date formats.

**Comment by tbm** [comment]
@zacchiro I have a patch I'd like to merge. Any objections?

https://github.com/tbm/ledger2beancount/commit/120868309e75215dde4237ef389752492a72d5c0

**Comment by zacchiro** [comment]
On Tue, Jun 23, 2020 at 04:07:29AM -0700, Martin Michlmayr wrote:
> @zacchiro I have a patch I'd like to merge. Any objections?

No, go ahead: having sane default(s) working out of the box in addition
to configurability sounds like a good thing to me too.

**Comment by tbm** [comment]
I forgot to reference this issue in commit 4509241acb487c68717.  This is working now.
