### ISSUE TITLE
Price directives with comments

### ISSUE THREAD

**Issue by xuhcc** [beancount/ledger2beancount#198]
ledger2beancount 2.3 fails to parse price directives with comments in ledger file:

```
P 2019/05/31 DASH 161.04 USD    ; CoinMarketCap #14
```

The parser now throws an error:

```
Unknown rest ; CoinMarketCap #14 in price directive: 2019-05-31 price DASH 161.04 USD at /usr/bin/ledger2beancount line 1414.
```

If I remove the comments everything works fine.

**Comment by tbm** [comment]
Right, that should of course be allowed. That's an unfortunate regression.  Thanks for pointing it out!
