### ISSUE TITLE
add a --version flag to emit the current version

### ISSUE THREAD

**Issue by zacchiro** [beancount/ledger2beancount#202]
as per title

(As usual, when implementing this feature, the most annoying thing is where to store the version information. `git describe` will provide it, but not in a way that would be available at install time. Would a string in the code that needs to be updated and committed every time, automatically or otherwise, be acceptable?)

**Comment by tbm** [comment]
Yeah. There are a couple of places that need to be updated when making a release.  Adding one more isn't going to hurt.  I should probably document it somewhere...
