### ISSUE TITLE
Accept transaction without any posting

### ISSUE THREAD

**Issue by tbm** [beancount/ledger2beancount#204]
https://hledger.org/journal.html#transactions

```
0 or more indented posting lines, describing what was transferred and the accounts involved (indented comment lines are also allowed, but not blank lines or non-indented lines).
```

**Comment by tbm** [comment]
```
hledger -f e print
2008/01/01 test
```

**Comment by tbm** [comment]
@simonmichael why is this allowed by hledger?  How is this used?

I wonder if this should be converted into some kind of note in beancount.

**Comment by simonmichael** [comment]
I saw no reason to disallow it, and thought it could be useful as a dated note. I do use it,eg to note events like signing up for subscriptions, or to record rough transaction info when I don't have time to do the postings.

**Comment by tbm** [comment]
Unfortunately I can't convert these to a beancount `note` because that requires an account name.

I could convert them to an `event` which is *probably* what those notes often are.  But I'm not sure I want to assume that.  And `event` in beancount can't have tags and metadata, which hledger transactions can have.

So I think I'll just put those transactions in comments in beancount.

**Comment by tbm** [comment]
To my surprise transactions with zero postings are allowed in ledger too.
