### ISSUE TITLE
Document how beancount_header is being interpreted

### ISSUE THREAD

**Issue by bratekarate** [beancount/ledger2beancount#250]
I just set up my configuration for `beancount_header`, which is a very handy option by the way. Though it seems that neither `~` expansion nor environment variables such as `$HOME` or `$XDG_CONFIG_HOME` are supported. I also tried to use a relative path and put the header file into `$XDG_CONFIG_HOME/ledger2beancount`, which also does not work. It is probably worth documenting that only absolute paths or paths relative to the directory where ledger2beancount is executed are possible.

**Comment by tbm** [comment]
> It is probably worth documenting that only absolute paths or paths relative to the directory where ledger2beancount is executed are possible.

Yeah, that sounds like a good idea.

I guess expanding `~` and `$HOME` would be nice.  Hmm.

**Comment by tbm** [comment]
I decided to expand `~` and `$...`, so your original use cases would have worked.

I don't easily see how to improve the docs, but I think with this change it's not needed anyway.
