### ISSUE TITLE
Can't parse date 2020/01/06 

### ISSUE THREAD

**Issue by iartarisi** [beancount/ledger2beancount#251]
I'm getting this error when running ledger2beancount without any configuration:

```
Can't parse date 2020/01/06 (set date_format and date_format_no_year) at /usr/bin/ledger2beancount line 169.
```

According to https://ledger2beancount.readthedocs.io/guide/#dates that format should be allowed, i.e. `YYYY/MM/DD`. Is the documentation wrong or am I not reading it right?

**Comment by tbm** [comment]
It works for me.  Are you sure you're using the latest version?

Actually, I think you have an old version because line 169 is something completely different now.

**Comment by iartarisi** [comment]
Hey, you're right. I'm on an old version: 2.0-1 from ubuntu.

Cheers.

**Comment by tbm** [comment]
There have been a lot of changes since 2.0.  I suggest you use the latest from GitHub.  If you run into issues with that, please open tickets.
